import { A } from '@solidjs/router'
import { Button, Card } from '../components'
import '../styles/landing.css'

// Landing page. Per design.md §"Aesthetic direction": warm beige + gold,
// asymmetric layout with hierarchy, no decorative blobs / centered-
// everything / glassmorphism.

export default function Home() {
  return (
    <main class="landing">
      <section class="landing-hero">
        <div class="landing-hero-text">
          <h1 class="landing-eyebrow">Gaia</h1>
          <p class="landing-headline">
            Idea to <em>shipped</em> SaaS in minutes.
          </p>
          <p class="landing-sub">
            An open-source template for the agent-native era. Solo operators get a working
            production stack — auth, payments, email, observability, and a harness that keeps the
            agent inside the lines.
          </p>
          <div class="landing-cta">
            <A href="/signup">
              <Button variant="primary">Start building</Button>
            </A>
            <A href="/login">
              <Button variant="ghost">Log in</Button>
            </A>
          </div>
        </div>
      </section>

      <section class="landing-pillars">
        <Card header="Real code, not low-code">
          Bun + Elysia + SolidStart + Drizzle + Polar. Type-safe end-to-end via Eden Treaty. No
          black-box runtime; you own the repo and ship to your own infra.
        </Card>
        <Card header="A harness, not a gym">
          References, hooks, ast-grep rules, and CI gates encode the conventions. The agent loads
          the right reference for the file it's editing — you don't repeat yourself in chat.
        </Card>
        <Card header="Made by a person">
          Warm typography. Restrained color. No glassmorphism, no purple gradients, no centered-
          everything. A taste signal that this wasn't generated by a brand-AI agent.
        </Card>
      </section>

      <footer class="landing-footer">
        <span>MIT-licensed. Use it, fork it, replace the parts you don't like.</span>
        <a href="https://github.com/henriquemeireles7/gaia">github.com/henriquemeireles7/gaia</a>
      </footer>
    </main>
  )
}
