// scripts/generate-tokens-css.ts — emits packages/ui/styles.css from tokens.ts.
//
// Walks the `semantic` object, flattens its keys to dotted paths, and writes
// CSS custom properties under `:root`. Re-run whenever tokens.ts changes
// (CI checks the result is committed via tokens/single-source rule).

import { writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { primitives, semantic } from '@gaia/ui/tokens'

type AnyObject = Record<string, unknown>

function flatten(obj: AnyObject, prefix: string[] = []): Array<[string, string]> {
  const out: Array<[string, string]> = []
  for (const [k, v] of Object.entries(obj)) {
    const path = [...prefix, k]
    if (v && typeof v === 'object' && !Array.isArray(v)) {
      out.push(...flatten(v as AnyObject, path))
    } else {
      out.push([path.join('-'), String(v)])
    }
  }
  return out
}

const banner = `/* DO NOT EDIT — generated by scripts/generate-tokens-css.ts from packages/ui/tokens.ts */\n`

const primitivesEntries = flatten(primitives as unknown as AnyObject, ['p'])
const semanticEntries = flatten(semantic as unknown as AnyObject, ['s'])

const lines = [
  banner,
  ':root {',
  '  /* Primitives */',
  ...primitivesEntries.map(([k, v]) => `  --${k}: ${v};`),
  '',
  '  /* Semantic */',
  ...semanticEntries.map(([k, v]) => `  --${k}: ${v};`),
  '}',
  '',
  '/* Base reset + body styles */',
  'html, body { margin: 0; padding: 0; }',
  'body {',
  '  font-family: var(--s-font-body);',
  '  font-size: var(--s-size-base);',
  '  color: var(--s-color-text-primary);',
  '  background: var(--s-color-bg-primary);',
  '  line-height: 1.5;',
  '}',
  'a { color: var(--s-color-accent-default); }',
  'a:hover { color: var(--s-color-accent-hover); }',
  'code { font-family: var(--s-font-code); font-size: 0.95em; }',
]

const out = `${lines.join('\n')}\n`
const target = join(process.cwd(), 'packages/ui/styles.css')
writeFileSync(target, out)
console.log(`tokens → CSS: wrote ${target}`)
