// scripts/generate-tokens-css.ts — emits packages/ui/styles.css from tokens.ts.
//
// Output matches the flat CSS variable naming in design.md / tokens.md:
//   --amber-50, --ink-900           (color primitives)
//   --bg-primary, --text-primary    (color semantics)
//   --space-0..10                   (spacing primitives)
//   --space-md, --space-lg          (spacing semantics)
//   --radius-md, --shadow-lg        (utility tiers)
//   --z-modal, --z-tooltip          (z-index — semantic by default)
//   --font-sans, --font-size-base   (typography)
//   --duration-short, --easing-enter (motion)
//
// Also emits an `@supports not (color: oklch(0 0 0))` block with hex
// fallbacks from `srgbFallback`, satisfying design.md §"P3 wide-gamut".
//
// Re-run whenever tokens.ts changes:
//   bun scripts/generate-tokens-css.ts
//
// `bun run check` runs scripts/check-tokens-sync.ts to verify the
// committed file matches what this script would produce.

import { spawnSync } from 'node:child_process'
import { readFileSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import {
  breakpoint,
  motion,
  opacity,
  primitives,
  radius,
  semantic,
  shadow,
  space,
  srgbFallback,
  typography,
  zIndex,
} from '@gaia/ui/tokens'

const BANNER =
  '/* DO NOT EDIT — generated by scripts/generate-tokens-css.ts from packages/ui/tokens.ts */'

function camelToKebab(s: string): string {
  return s.replace(/([A-Z])/g, '-$1').toLowerCase()
}

export function buildCSS(): string {
  const lines: string[] = []
  lines.push(BANNER, '')
  lines.push(':root {')

  // ── Primitives ────────────────────────────────────────────────
  lines.push('  /* Color primitives */')
  for (const [family, shades] of Object.entries(primitives)) {
    for (const [shade, value] of Object.entries(shades)) {
      lines.push(`  --${family}-${shade}: ${value};`)
    }
  }

  lines.push('', '  /* Spacing primitives */')
  for (const [k, v] of Object.entries(space)) {
    lines.push(`  --space-${k}: ${v};`)
  }

  lines.push('', '  /* Radius */')
  for (const [k, v] of Object.entries(radius)) {
    lines.push(`  --radius-${k}: ${v};`)
  }

  lines.push('', '  /* Shadow */')
  for (const [k, v] of Object.entries(shadow)) {
    lines.push(`  --shadow-${k}: ${v};`)
  }

  lines.push('', '  /* Z-index */')
  for (const [k, v] of Object.entries(zIndex)) {
    lines.push(`  --z-${camelToKebab(k)}: ${v};`)
  }

  lines.push('', '  /* Breakpoints */')
  for (const [k, v] of Object.entries(breakpoint)) {
    lines.push(`  --breakpoint-${k}: ${v};`)
  }

  lines.push('', '  /* Opacity */')
  for (const [k, v] of Object.entries(opacity)) {
    lines.push(`  --opacity-${k}: ${v};`)
  }

  lines.push('', '  /* Typography — family */')
  lines.push(`  --font-serif: ${typography.family.serif};`)
  lines.push(`  --font-sans: ${typography.family.sans};`)
  lines.push(`  --font-mono: ${typography.family.mono};`)

  lines.push('', '  /* Typography — size */')
  for (const [k, v] of Object.entries(typography.size)) {
    lines.push(`  --font-size-${k}: ${v};`)
  }

  lines.push('', '  /* Typography — weight */')
  for (const [k, v] of Object.entries(typography.weight)) {
    lines.push(`  --font-weight-${k}: ${v};`)
  }

  lines.push('', '  /* Typography — leading */')
  for (const [k, v] of Object.entries(typography.leading)) {
    lines.push(`  --leading-${k}: ${v};`)
  }

  lines.push('', '  /* Typography — tracking */')
  for (const [k, v] of Object.entries(typography.tracking)) {
    lines.push(`  --tracking-${k}: ${v};`)
  }

  lines.push('', '  /* Motion — duration */')
  for (const [k, v] of Object.entries(motion.duration)) {
    lines.push(`  --duration-${k}: ${v};`)
  }

  lines.push('', '  /* Motion — easing */')
  for (const [k, v] of Object.entries(motion.easing)) {
    lines.push(`  --easing-${k}: ${v};`)
  }

  // ── Semantic ──────────────────────────────────────────────────
  lines.push('', '  /* Semantic — background */')
  lines.push(`  --bg-primary: ${semantic.color.bg.primary};`)
  lines.push(`  --bg-secondary: ${semantic.color.bg.secondary};`)
  lines.push(`  --bg-tertiary: ${semantic.color.bg.tertiary};`)
  lines.push(`  --bg-surface: ${semantic.color.bg.surface};`)

  lines.push('', '  /* Semantic — text */')
  lines.push(`  --text-primary: ${semantic.color.text.primary};`)
  lines.push(`  --text-secondary: ${semantic.color.text.secondary};`)
  lines.push(`  --text-muted: ${semantic.color.text.muted};`)

  lines.push('', '  /* Semantic — accent */')
  lines.push(`  --accent: ${semantic.color.accent.default};`)
  lines.push(`  --accent-hover: ${semantic.color.accent.hover};`)

  lines.push('', '  /* Semantic — status */')
  lines.push(`  --success: ${semantic.color.status.success};`)
  lines.push(`  --error: ${semantic.color.status.error};`)
  lines.push(`  --warning: ${semantic.color.status.warning};`)
  lines.push(`  --info: ${semantic.color.status.info};`)

  lines.push('', '  /* Semantic — border */')
  lines.push(`  --border-subtle: ${semantic.color.border.subtle};`)
  lines.push(`  --border-default: ${semantic.color.border.default};`)
  lines.push(`  --border-emphasis: ${semantic.color.border.emphasis};`)

  lines.push('', '  /* Semantic — spacing */')
  for (const [k, v] of Object.entries(semantic.spacing)) {
    lines.push(`  --space-${k}: ${v};`)
  }

  lines.push('}')

  // ── sRGB fallback for older browsers ──────────────────────────
  lines.push('')
  lines.push('/* sRGB fallback for browsers without OKLCH. Modern browsers ignore this block. */')
  lines.push('@supports not (color: oklch(0 0 0)) {')
  lines.push('  :root {')
  for (const [key, hex] of Object.entries(srgbFallback)) {
    lines.push(`    --${key}: ${hex};`)
  }
  lines.push('  }')
  lines.push('}')

  // ── Reduced-motion (design.md §"Accessibility") ───────────────
  lines.push('')
  lines.push('@media (prefers-reduced-motion: reduce) {')
  lines.push('  *, *::before, *::after {')
  lines.push('    animation-duration: 0.01ms !important;')
  lines.push('    animation-iteration-count: 1 !important;')
  lines.push('    transition-duration: 0.01ms !important;')
  lines.push('    scroll-behavior: auto !important;')
  lines.push('  }')
  lines.push('}')

  // ── Base reset + body ─────────────────────────────────────────
  lines.push('')
  lines.push('/* Base reset + body. Components import this once at app entry. */')
  lines.push('html, body { margin: 0; padding: 0; }')
  lines.push('body {')
  lines.push('  font-family: var(--font-sans);')
  lines.push('  font-size: var(--font-size-base);')
  lines.push('  line-height: var(--leading-relaxed);')
  lines.push('  color: var(--text-primary);')
  lines.push('  background: var(--bg-primary);')
  lines.push('  -webkit-font-smoothing: antialiased;')
  lines.push('  -moz-osx-font-smoothing: grayscale;')
  lines.push('}')
  lines.push('h1, h2, h3, h4 {')
  lines.push('  font-family: var(--font-serif);')
  lines.push('  line-height: var(--leading-tight);')
  lines.push('  letter-spacing: var(--tracking-tight);')
  lines.push('  margin: 0;')
  lines.push('}')
  lines.push('a { color: var(--accent); text-decoration: none; }')
  lines.push('a:hover { color: var(--accent-hover); text-decoration: underline; }')
  lines.push('code, pre { font-family: var(--font-mono); font-size: 0.95em; }')
  lines.push('*:focus-visible {')
  lines.push('  outline: none;')
  lines.push('  box-shadow: 0 0 0 2px var(--bg-primary), 0 0 0 4px var(--accent);')
  lines.push('  border-radius: var(--radius-sm);')
  lines.push('}')

  return `${lines.join('\n')}\n`
}

// Emit the formatted CSS by passing the raw output through oxfmt — the
// project's CSS formatter — so the file is byte-stable across regen and
// matches `bun run check:format`.
export function buildFormattedCSS(): string {
  const raw = buildCSS()
  const tmp = join(tmpdir(), `gaia-tokens-${process.pid}-${Date.now()}.css`)
  writeFileSync(tmp, raw)
  const result = spawnSync('bunx', ['oxfmt', tmp], { stdio: 'pipe' })
  if (result.status !== 0) {
    throw new Error(`oxfmt failed:\n${result.stderr?.toString() ?? ''}`)
  }
  return readFileSync(tmp, 'utf-8')
}

if (import.meta.main) {
  const out = buildFormattedCSS()
  const target = join(process.cwd(), 'packages/ui/styles.css')
  writeFileSync(target, out)
  console.log(`tokens → CSS: wrote ${target}`)
}
