// packages/ui/tokens.ts — design tokens, single source of truth.
//
// See .gaia/reference/design.md (the why + aesthetic) and tokens.md (the
// machine-readable contract). This file is the authoritative source; the
// CSS counterpart at ./styles.css is regenerated by
// `bun scripts/generate-tokens-css.ts` and verified by
// `scripts/check-tokens-sync.ts` in the check pipeline.
//
// Three-tier architecture (tokens.md §"three-tier architecture"):
//   1. PRIMITIVES — raw values, descriptive names ('amber.500'), never
//      applied directly in components.
//   2. SEMANTIC   — meaning-bearing aliases ('text.primary', 'accent').
//      What components reference. Swap primitives → re-theme.
//   3. COMPONENT  — only when semantic tokens cannot express specificity.
//      Not present yet; add per-component as needed.
//
// Color uses OKLCH (perceptual uniformity, P3-ready). sRGB fallback hex
// codes are tracked alongside in `srgbFallback` so the CSS generator can
// emit `@supports not (color: oklch(0 0 0))` blocks for older browsers.

// ─── Tier 1: Primitives ─────────────────────────────────────────

export const primitives = {
  amber: {
    50: 'oklch(0.98 0.02 80)',
    100: 'oklch(0.95 0.03 75)',
    200: 'oklch(0.89 0.05 75)',
    400: 'oklch(0.80 0.06 70)',
    500: 'oklch(0.72 0.08 70)',
    600: 'oklch(0.63 0.09 55)',
  },
  ink: {
    400: 'oklch(0.70 0.02 70)',
    600: 'oklch(0.48 0.02 60)',
    900: 'oklch(0.18 0.01 60)',
  },
  sage: {
    500: 'oklch(0.65 0.09 140)',
  },
  terracotta: {
    500: 'oklch(0.60 0.14 30)',
  },
  gold: {
    500: 'oklch(0.78 0.14 85)',
  },
  slate: {
    400: 'oklch(0.65 0.03 240)',
  },
} as const

// sRGB fallbacks per design.md §"Color → Primitives". Keys mirror the
// flat CSS variable name (without the `--` prefix) so the generator can
// look them up by family-shade.
export const srgbFallback = {
  'amber-50': '#FAF8F5',
  'amber-100': '#F2EDE6',
  'amber-200': '#E8E0D4',
  'amber-400': '#D5B07F',
  'amber-500': '#C4956A',
  'amber-600': '#B07D4F',
  'ink-400': '#A69D91',
  'ink-600': '#6B6258',
  'ink-900': '#1A1714',
  'sage-500': '#6B8F5E',
  'terracotta-500': '#C25B4A',
  'gold-500': '#D4A843',
  'slate-400': '#7B8FA6',
} as const

export const space = {
  0: '0px',
  1: '2px',
  2: '4px',
  3: '8px',
  4: '16px',
  5: '24px',
  6: '32px',
  7: '48px',
  8: '64px',
  9: '96px',
  10: '128px',
} as const

export const radius = {
  none: '0',
  sm: '8px',
  md: '12px',
  lg: '16px',
  full: '9999px',
} as const

export const shadow = {
  none: 'none',
  sm: '0 1px 2px 0 oklch(0.18 0.01 60 / 0.05)',
  md: '0 4px 6px -1px oklch(0.18 0.01 60 / 0.08), 0 2px 4px -2px oklch(0.18 0.01 60 / 0.04)',
  lg: '0 10px 15px -3px oklch(0.18 0.01 60 / 0.08), 0 4px 6px -4px oklch(0.18 0.01 60 / 0.04)',
  xl: '0 20px 25px -5px oklch(0.18 0.01 60 / 0.08), 0 8px 10px -6px oklch(0.18 0.01 60 / 0.04)',
  inner: 'inset 0 2px 4px 0 oklch(0.18 0.01 60 / 0.06)',
} as const

export const zIndex = {
  base: '0',
  dropdown: '100',
  sticky: '200',
  modalBackdrop: '300',
  modal: '400',
  toast: '500',
  tooltip: '600',
} as const

export const breakpoint = {
  sm: '640px',
  md: '768px',
  lg: '1024px',
} as const

export const opacity = {
  disabled: '0.5',
  subtle: '0.6',
  muted: '0.75',
  full: '1',
} as const

export const typography = {
  family: {
    serif: '"Instrument Serif", Georgia, serif',
    sans: '"Instrument Sans", system-ui, -apple-system, sans-serif',
    mono: '"Geist Mono", "Fira Code", Menlo, monospace',
  },
  size: {
    xs: '0.75rem',
    sm: '0.875rem',
    base: '1rem',
    lg: '1.1875rem',
    xl: '1.5rem',
    '2xl': '2rem',
    '3xl': '2.25rem',
    '4xl': 'clamp(2.5rem, 2rem + 2vw, 3rem)',
    hero: 'clamp(2.75rem, 2rem + 3vw, 3.5rem)',
  },
  weight: {
    regular: '400',
    medium: '500',
    semibold: '600',
    bold: '700',
  },
  leading: {
    tight: '1.2',
    normal: '1.5',
    relaxed: '1.6',
    loose: '1.75',
  },
  tracking: {
    tight: '-0.02em',
    normal: '0',
    wide: '0.025em',
  },
} as const

export const motion = {
  duration: {
    instant: '0ms',
    micro: '150ms',
    short: '250ms',
    medium: '400ms',
    long: '500ms',
  },
  easing: {
    enter: 'cubic-bezier(0.25, 1, 0.5, 1)',
    exit: 'cubic-bezier(0.7, 0, 0.84, 0)',
    move: 'cubic-bezier(0.65, 0, 0.35, 1)',
  },
} as const

// ─── Tier 2: Semantic ────────────────────────────────────────────

export const semantic = {
  color: {
    bg: {
      primary: primitives.amber[50],
      secondary: primitives.amber[100],
      tertiary: primitives.amber[200],
      surface: '#ffffff',
    },
    text: {
      primary: primitives.ink[900],
      secondary: primitives.ink[600],
      muted: primitives.ink[400],
    },
    accent: {
      default: primitives.amber[500],
      hover: primitives.amber[600],
    },
    status: {
      success: primitives.sage[500],
      error: primitives.terracotta[500],
      warning: primitives.gold[500],
      info: primitives.slate[400],
    },
    border: {
      subtle: primitives.amber[200],
      default: primitives.amber[200],
      emphasis: primitives.amber[400],
    },
  },
  spacing: {
    xs: space[2],
    sm: space[3],
    md: space[4],
    lg: space[5],
    xl: space[6],
    '2xl': space[7],
    '3xl': space[8],
    '4xl': space[9],
  },
  radius,
  shadow,
  zIndex,
  breakpoint,
  opacity,
  typography,
  motion,
} as const

export type Tokens = typeof semantic
